services:
  - type: web
    name: expensetracer-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: expensetracer-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE
        fromService:
          name: expensetracer-backend
          type: web
          property: hostport
      - key: REACT_APP_API_URL
        value: https://${REACT_APP_API_BASE}/api/v1
