services:
  # Backend service
  - type: web
    name: expensetracer-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    autoDeploy: true

  # Frontend service
  - type: web
    name: expensetracer-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: expensetracer-backend
          property: url
    autoDeploy: true

# Database (if you want to use Render's managed database)
databases:
  - name: expensetracer-db
    databaseName: expensetracer
    user: expensetracer_user

